### ISSUE TITLE
Configure email aliases on bastion

### ISSUE THREAD

**Issue by nphilipp** [fedora-infra/aaa-tracker#30]
With FAS, email aliases were installed locally through the `fasClient` script. Instead, configure postfix to look up aliases, virtual tables (whatever fits best) in LDAP, cf.:

* http://www.postfix.org/LDAP_README.html
* http://www.postfix.org/aliases.5.html
* http://www.postfix.org/virtual.5.html
* http://www.postfix.org/ldap_table.5.html

**Comment by arrfab** [comment]
I guess there are multiple ways to solve that. 

 * If the "bastion" host has direct access to ldap, yes you can query on each requests, but it can easily "overload" ldap due to number of queries, so something to keep in mind
 * If it doesn't (ipa/ldap isn't publicly reachable) the other way is to query through fasjson and put that in postfix directly (and just reload aliases and/or virtusertable) : that's the option I took for CentOS as our mail/MX server *can't* reach IPA/Ldap but can still query fasjson : see the following commit (in Staging branch for now) : https://github.com/CentOS/ansible-role-postfix/commit/5b6bf0eebedd2c126aad3a3af1cea4ae4425750b (if you look at the postfix role, it had the same feature to query FAS so just adapted the script to use kerberos and fasjson)

**Comment by nphilipp** [comment]
One other thing to keep in mind: `fasClient -ia` installs `etc/aliases` from a template which contains hard-coded aliases, this needs to be migrated as well.

**Comment by StephenCoady** [comment]
PR here: https://pagure.io/fedora-infra/ansible/pull-request/408
