### ISSUE TITLE
Check how to make FAS read-only

### ISSUE THREAD

**Issue by abompard** [fedora-infra/aaa-tracker#34]
We plan to keep FAS read-only for a while, but we need to figure out how to actually do it.

**Comment by ryanlerch** [comment]
We should also investigate how to check the logs for who is using the read only FAS (probably specifically the API), after it goes read-only.

**Comment by StephenCoady** [comment]
It looks like we might be able to just remove INSERT, UPDATE, DELETE for the `fas` user on `db-fas01`. 

Some open questions though: 
* what will the UX be like
* do we care? 

If we are putting a read-only banner of some sort across FAS then we might be OK eating errors.

Also depending on the db setup, we might be able to leave INSERT permissions for the logging table. I need to investigate this further.

**Comment by StephenCoady** [comment]
@markobrien1 and I have spent the last day or so deploying FAS in staging under a different URL to test this. It's available [here](https://admin-test.stg.fedoraproject.org/accounts) for anyone that is interested, although probably not for long.

We changed permissions for the `fas` user so that it no longer has access to write to _some_ but not all tables. We believe that some tables in the database will cause FAS to not work at all if not available for writing. Examples are logging and access tables.

We have tested this version of FAS and it works well, not allowing any write actions. However, the caveat is that any attempted write actions will cause a 500 error to be displayed by the application itself. The pod is fine and does not crash thankfully. We think this is OK though, as there will be a banner at the top of each page stating that it is in a read-only state now (maybe we could extend that @ryanlerch to inform users they will see a 500 if they try?). Another (small) consideration is that, due to the FAS code, certain things like email notifications of changes may still happen even though the change itself was not recorded in the DB. A user changing their details is one example.

Overall I think this is a good solution and unless anyone has any comments then Mark and I will have these changes ready for production.

@ryanlerch you mentioned we should check if it's possible to identify people who haven't migrated and we think it is. There is a `requests` table in the DB which logs access from applications so we can manually check that closer to turning FAS off completely.

FYI @nirik @pypingou

**Comment by StephenCoady** [comment]
DB steps for completeness:

```
--
-- Make fas read only
--
 
REVOKE ALL PRIVILEGES on people from fas;
GRANT SELECT on people to fas;
GRANT update (last_seen) on people to fas;
 
REVOKE ALL PRIVILEGES on groups from fas;
GRANT SELECT on groups to fas;
 
REVOKE ALL PRIVILEGES on group_roles from fas;
GRANT SELECT on group_roles to fas;
 
REVOKE ALL PRIVILEGES on person_roles from fas;
GRANT SELECT on person_roles to fas;
 
REVOKE ALL PRIVILEGES on person_roles_fpca from fas;
GRANT SELECT on person_roles_fpca to fas;
 
REVOKE ALL PRIVILEGES on bugzilla_queue from fas;
GRANT SELECT on bugzilla_queue to fas;
 
```

**Comment by markobrien1** [comment]
I have stopped the emails from being sent. I changed the smtp servers to bastion-dummy in the configmap and redeployed and they are no longer sent. This will need to go into ansible along with the sql above
